//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        public int ApptID { get; set; }
        public int StudentID { get; set; }
        public int CounselorID { get; set; }
        public System.DateTime ApptDateTime { get; set; }
        public string ApptApproval { get; set; }
        public string ApptLocation { get; set; }
        public string ApptDescription { get; set; }
        public string ApptLink { get; set; }
    }
}
