//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNSELORACCOUNTINFO
    {
        public int AccountID { get; set; }
        public int CounselorID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
