//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTS1
    {
        public int EventID { get; set; }
        public string EventName { get; set; }
        public byte[] EventImage { get; set; }
        public string EventLocation { get; set; }
        public string EventDescription { get; set; }
        public string EventLink { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public int RSVPCount { get; set; }
        public string EventApproval { get; set; }
    }
}
