//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLC
    {
        public int TLCID { get; set; }
        public string RAMID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public string Major { get; set; }
        public string Standing { get; set; }
        public string CurrentGPA { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string HomeAddress { get; set; }
        public string Status { get; set; }
        public byte[] ProfilePicture { get; set; }
        public string Pronouns { get; set; }
        public string AboutMe { get; set; }
        public string Goals { get; set; }
    }
}
