//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT
    {
        public int DocID { get; set; }
        public string SCTAKey { get; set; }
        public string DocName { get; set; }
        public string DocDescription { get; set; }
        public string Feedback { get; set; }
    }
}
